#!/bin/sh
# Spawn a getty process based on the configuration in /proc/cmdline

# getting variables from /proc/cmdline
consoles=$(cat /proc/cmdline | tr " " "\n" | grep ^console= | cut -d= -f2)
echo "$consoles" | while read console; do
    tty=$(echo $console | cut -d, -f1)
    attrs=$(echo $console | cut -d, -f2)
    baud=$(echo $attrs | cut -dn -f1)

    # start getty for the first console= entry
    exec /sbin/getty -L ${tty:-ttyS0} ${baud:-9600} vt220
done
